-- 회원정보

  CREATE TABLE "TJOEUNIT"."MEMBER" 
   (	"ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"JUMIN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TELEPHONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"AGE" NUMBER(*,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"POSTCODE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"PHOTO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DETAILADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
  -- 모임 
  
    CREATE TABLE "TJOEUNIT"."PARTY" 
   (	"IDX" NUMBER(*,0) NOT NULL ENABLE, 
	"ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
	"PLACE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PARTYGENDER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEALDATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"THUMBNAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ACHOLCHK" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IP" CHAR(15 BYTE), 
	"MINLIMITAGE" NUMBER(*,0) DEFAULT 19 NOT NULL ENABLE, 
	"MAXLIMITAGE" NUMBER(*,0) DEFAULT 100 NOT NULL ENABLE, 
	"LIMITNUM" NUMBER(*,0) DEFAULT 2 NOT NULL ENABLE, 
	"SHOW" VARCHAR2(10 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	"DELETEREPORT" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"MASTERPHOTO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "PARTY_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  
-- 파티 참여 TABLE

    CREATE TABLE "TJOEUNIT"."REPLE" 
   (	"REPLEIDX" NUMBER(*,0), 
	"ORIGINIDX" NUMBER(*,0) NOT NULL ENABLE, 
	"MASTERID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REPLEID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REPLE" VARCHAR2(500 BYTE), 
	"WRITEDATE" TIMESTAMP (6) DEFAULT sysdate, 
	"REPLEIP" CHAR(15 BYTE), 
	"FIX" VARCHAR2(3 BYTE) DEFAULT 'N', 
	"REPLENICKNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"REPLEGENDER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"REPLEAGE" NUMBER(*,0), 
	"REPLELIMITNUM" NUMBER(*,0), 
	"REPLECOUNTNUM" NUMBER(*,0), 
	"REPLEPHOTO" VARCHAR2(200 BYTE), 
	 CONSTRAINT "REPLE_PK" PRIMARY KEY ("REPLEIDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "IAN"."REPLE"."REPLEIDX" IS '고유값';
   COMMENT ON COLUMN "IAN"."REPLE"."ORIGINIDX" IS '종속된 방idx';
   COMMENT ON COLUMN "IAN"."REPLE"."MASTERID" IS '모임장';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLEID" IS '모임원 ID';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLE" IS '글내용';
   COMMENT ON COLUMN "IAN"."REPLE"."WRITEDATE" IS '작성일';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLEIP" IS '작성자IP';
   COMMENT ON COLUMN "IAN"."REPLE"."FIX" IS '모임 확정';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLENICKNAME" IS '모임원 닉네임';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLEGENDER" IS '모임원 성별';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLEAGE" IS '모임원 나이';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLELIMITNUM" IS '모임원 제한나이';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLECOUNTNUM" IS '리플카운트넘';
   COMMENT ON COLUMN "IAN"."REPLE"."REPLEPHOTO" IS '모임원 사진';
   
   drop sequence reple_idx_seq;
   create sequence reple_idx_seq;
   
   
-- 신고

     CREATE TABLE "TJOEUNIT"."REPORT" 
   (	"REPORTIDX" NUMBER NOT NULL ENABLE, 
	"REPORTID" VARCHAR2(100 BYTE), 
	 CONSTRAINT "REPORT_PK" PRIMARY KEY ("REPORTIDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

-- 평가점수

  CREATE TABLE "TJOEUNIT"."SCORE" 
   (	"SCOREID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PROMISE" NUMBER NOT NULL ENABLE, 
	"MANNER" NUMBER NOT NULL ENABLE, 
	"CLEAN" NUMBER NOT NULL ENABLE, 
	"SCORETOTAL" NUMBER NOT NULL ENABLE, 
	"SCORECOUNT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SCORE_PK" PRIMARY KEY ("SCOREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;